### ISSUE TITLE
When update 2023.01 release burpsuite?

### ISSUE THREAD

**Issue by decuple-dream** [PortSwigger/burp-extensions-montoya-api#21]
Hello. Team! An error occurs when you build and load the HttpHandlerExample to use the latest Montoya API.

```
java.lang.ClassNotFoundException: burp.api.montoya.http.handler.HttpHandler
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at example.httphandler.HttpHandlerExample.initialize(HttpHandlerExample.java:20)
	at burp.r16.Z(Unknown Source)
	at burp.v4r.v(Unknown Source)
	at burp.v4x.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I think it's because my burp version is 2022.12.05.
Can I download the latest release version?

**Comment by SeanBurnsUK** [comment]
Version 2023.1 will be released in the next few days.

**Comment by SeanBurnsUK** [comment]
@decuple-dream 2023.1 is now released on the early adopter channel.

**Comment by decuple-dream** [comment]
@SeanBurnsUK  Thank you! <3
