### ISSUE TITLE
montoya-api not compatible with burp pro headless?

### ISSUE THREAD

**Issue by petrabrunner** [PortSwigger/burp-extensions-montoya-api#22]
Hi, 

is it possible that montoya-api is not compatible with burp PRO (2022.12.15) in headless mode? 
when trying to load an extension (without a jython version) I get this exception: 

`java.lang.ClassNotFoundException: burp.BurpExtender
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at burp.rw.a(Unknown Source)
        at burp.rw.<init>(Unknown Source)
        at burp.fdd.a(Unknown Source)
        at burp.akr.lambda$load$0(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)`

loading this extension in burp Pro (w.o. -Djava.awt.headless=true flag) works like a charm.

**Comment by Hannah-PortSwigger** [comment]
Hi

Could you drop us an email at support@portswigger.net with some more information, please?

If you could provide your extension and diagnostics info ("Help > Diagnostics" or `--diagnostics` flag), that would be helpful.

**Comment by petrabrunner** [comment]
done. I provided the diagnostics and some basic details about my extension.
